name: 'build tools setup action'
runs:
  using: "composite"
  steps:
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: 'stable'

    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-make
